### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe-storybook#10]
![image](https://user-images.githubusercontent.com/1889830/53651616-022d1700-3c15-11e9-95b7-f11e8d6eb8f3.png)

States
- Selected
- Not selected

**Comment by grdunn** [comment]
@stuartromanek should this be handled as a `radio` input, with fancy labels?

**Comment by abea** [comment]
I created a boolean input in #39 that we should be able to repurpose for this.

**Comment by abea** [comment]
I don't mean that this is done, but that we can reuse stuff from the boolean. Some additional variant styling is needed to match this use case.
