### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe-storybook#16]
Possible permutations of the modal
![wireframe](https://user-images.githubusercontent.com/1889830/53653477-5df99f00-3c19-11e9-885e-f2a059cb0b92.png)

Modals can also take up some arbitrary non-full screen width

![desktop hd copy 7](https://user-images.githubusercontent.com/1889830/53660048-0106e480-3c2b-11e9-9012-f463742f6559.png)

In in practice
![desktop hd copy 6](https://user-images.githubusercontent.com/1889830/53660062-05cb9880-3c2b-11e9-8412-05e3c154238b.png)
![desktop hd copy 6](https://user-images.githubusercontent.com/1889830/53653510-7669b980-3c19-11e9-8e77-993f77185b3e.png)
![desktop hd copy 17](https://user-images.githubusercontent.com/1889830/53653512-7669b980-3c19-11e9-84f8-a45d352f3883.png)
![manage pieces copy 4](https://user-images.githubusercontent.com/1889830/53653513-7669b980-3c19-11e9-945c-5296d545301f.png)
![manage pieces](https://user-images.githubusercontent.com/1889830/53653514-7669b980-3c19-11e9-88aa-c73df96e2a91.png)

**Comment by abea** [comment]
I approached #43 adding a big `slot` for the main area rather than dividing it up there. I think we'll have a few different components for the main use case groups.
