### ISSUE TITLE
Modal Breadcrumbs

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe-storybook#26]
![image](https://user-images.githubusercontent.com/1889830/53661423-41b42d00-3c2e-11e9-9c11-826ddfa3061b.png)

![image](https://user-images.githubusercontent.com/1889830/53661442-4d9fef00-3c2e-11e9-988e-b883af04dfe1.png)

Design needs refinement

**Comment by abea** [comment]
Also some of this in #43
