### ISSUE TITLE
Popover

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe-storybook#4]
![image](https://user-images.githubusercontent.com/1889830/53650347-58e52180-3c12-11e9-8228-aec736fc94d0.png)

Popover Types
- From top left
- From top right
- from top center
- from bottom left
- from bottom right
- from bottom center

**Comment by abea** [comment]
I just got going on this using v-tooltip. https://github.com/Akryum/v-tooltip/. It seems mature and is working to a third version. Seems flexible enough for our needs.
