### ISSUE TITLE
Context menu positioning

### ISSUE THREAD

**Issue by stuartromanek** [apostrophecms/apostrophe-storybook#89]
> _A context menu!_

![bx6SJjbEWr](https://user-images.githubusercontent.com/1889830/83567800-30706500-a4f0-11ea-9516-578176d3ae03.gif)

The current organization of the apostrophe 3 front-end makes it difficult to position a context menu in all the ways you'd naturally expect.

Ideally a context menu would:
- Remain attached to its parent while scrolling
- Appear above all sibling UI
- Not be clipped by overflow settings

As a tidy Vue component it should also be bundled with its button for a direct line of communication when toggling its opened/closed state.

The current implementation is a fussy calculation of the exact X,Y position on the page and having the element `position: fixed`. This breaks down when a user scrolls (and with the multiple scroll contexts of a modal is even more fussy to try to correct on scroll).

> Why not go absolute from the start?

Absolute provided its own challenges, like improper sibling z-index layering and context menu ui being clipped by the enforced individual scroll contexts of the apostrophe modals.
![image](https://user-images.githubusercontent.com/1889830/83569172-13d52c80-a4f2-11ea-8422-8d1e745b6838.png)

> _whoops, where'd the tag interface go?_

Looking for suggestions from @abea @gregvanbrug @breyell @falkodev 

Component located in `src/components/contextMenu/AposContextMenu.vue`

**Comment by abea** [comment]
Ideally we would use a library that uses `fixed` and follows the triggering element on scroll to prevent any possibility of clipping. `absolute` is still workable, though. Part of it is choosing what the tip alignment based on order in the toolbar. In the screenshot above, switching the tip-alignment would fix that clipping. The problem will be in smaller screens.

**Comment by stuartromanek** [comment]
small screens could clip things but also any new uses of context menus that appear other places (i could imagine them being used as part of a choose, which would appear in the left rail of a modal. Or as part of the media manager Selected interface, which appears in the right rail. both these places would be clipped quickly even on a large screen)
